[package]
name = "wasm-pack"
description = "📦✨ your favorite rust -> wasm workflow tool!"
version = "0.10.3"
authors = ["Ashley Williams <ashley666ashley@gmail.com>", "Jesper Håkansson <jesper@jesperh.se>"]
repository = "https://github.com/rustwasm/wasm-pack.git"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["wasm"]
documentation = "https://rustwasm.github.io/wasm-pack/"

[dependencies]
anyhow = "1.0.66"
atty = "0.2.11"
cargo_metadata = "0.15"
console = "0.6.1"
dialoguer = "0.10"
curl = "0.4.13"
env_logger = { version = "0.9", default-features = false }
human-panic = "1.0.1"
glob = "0.3"
log = "0.4.6"
openssl = { version = '0.10.11', optional = true }
parking_lot = "0.12"
reqwest = { version = "0.11.12", features = ["blocking"] }
semver = "1"
serde = "1.0.74"
serde_derive = "1.0.74"
serde_ignored = "0.1"
serde_json = "1.0.26"
strsim = "0.10"
siphasher = "0.3"
structopt = "0.3"
toml = "0.5"
which = "4.3.0"
binary-install = "0.1.0"
walkdir = "2"
chrono = "0.4.6"

[dev-dependencies]
assert_cmd = "2"
lazy_static = "1.1.0"
predicates = "2"
serial_test = "0.9"
tempfile = "3"

[features]
# OpenSSL is vendored by default, can use system OpenSSL through feature flag.
default = ['openssl/vendored']

# Treat compiler warnings as a build error.
# This only runs in CI by default
strict = ['openssl/vendored']
sys-openssl = ['openssl']
# Keeping feature for users already using this feature flag
vendored-openssl = ['openssl/vendored']
